
<style>
    main {
        margin-left: 5vw;
    }

    #core_elements {
        display: flex;
        justify-content: center;
        align-content: flex-end;
    }
    /* style des canvas*/
    canvas {
        box-shadow: 3px 3px 3px 3px rgba(0, 0, 0, 0.5);
        margin: 1vw;
        background: white;

    }

    #palette {
        cursor: crosshair;
        display: none;

        align-self: flex-end;
        border: 2px ridge rgba(93, 155, 118, 0.22)
    }

    #colo_selected {
        display:inline-block;
        background:black;
        height:2vw;
        width:2vw;
        border-radius:50%;
    }

    #output {
        border-radius: 50px;
        display: inline-block;
        height: 20px;
        width: 5px;
        background-color: black;
    }

    /* */
    #outils {
        display: inline-block;
        width: 10vw;
        height: 600px;
        background: rgba(128, 128, 128, 0.36);
        border-radius: .8em;
        box-shadow: 3px 3px 3px 3px rgba(0, 0, 0, 0.33);
        border: 5px solid rgba(255, 255, 255, 0.34);
        align-self: center;
    }

    INPUT[type="range"] {
        width: 100px;
    }

    #outils div {
        display: flex;
        justify-content: space-around;
        flex-wrap: wrap;
        font-size: 1.5rem;
    }

    #outils div button {
        background-color: rgba(131, 201, 245, 0.52);
        border-radius: 50%;
    }

    #outils div button:hover {
        opacity: 0.5;
        box-shadow: 3px 3px 3px 3px rgba(17, 16, 38, 0.58);
    }

    #effects {
        flex-basis: 100%
    }

    span {
        font-size: 2rem;
    }
    /* style pour les boutons*/
    button:hover {
        cursor: pointer;
        background-color: rgba(26, 240, 255, 0.48);
    }

    /* style de la ligne couleurs*/
    #Couleurs {
        display: flex;
        justify-content: space-around;
    }

    #Couleurs div {
        width: 2vw;
        height:2vw;
        margin: 10px 5px;
        border-radius: 50%;
    }

    #Couleurs div:hover {
        box-shadow: 3px 3px 3px 3px rgba(17, 16, 38, 0.58);
    }
    .selected {
        border : 5px solid gray;
    }
    #black {
        cursor: pointer;
        background-color: black;
    }

    #Brown {
        cursor: pointer;
        background-color: brown;
    }

    #Red {
        cursor: pointer;
        background-color: red;
    }

    #Yellow {
        cursor: pointer;
        background-color: yellow;
    }

    #Green {
        cursor: pointer;
        background-color: green;
    }

    #blueSoft {
        cursor: pointer;
        background-color: deepskyblue;
    }

    #blueHard {
        cursor: pointer;
        background-color: blue;
    }
</style>
    <h1><i class="fas fa-paint-brush"></i>ardoise magique</h1>
    <section id="core_elements">
        <canvas id="content" width="800" height="600"></canvas>

        <div id="outils">
            <h4>outils</h4>
            <div>
                <button id="Gomme" title="Gomme"><i class="fas fa-eraser"></i></button>
                <button id="pipette" title="Pipette"><i class="fas fa-eye-dropper"></i></button>
                <button id="eraser" title="effacer le dessein">reset</button>
                <p><span id="colo_selected"></span></p>
                <p>
                    <input type="range" min="1" max="50">
                    <span id="output"></span>
                </p>
                <select id="effects" title="effets tracée">
                    <option value="pencil">pencil</option>
                    <option value="brush">brush</option>
                    <option value="toile">toile</option>
                    <option value="rectangle">rectangle</option>
                </select>
                <span title="effet ombres">shadow : <input id="shadow" type="checkbox"></span>
                <canvas id="palette" width="170px" height="50"></canvas>
            </div>

        </div>


    </section>

    <article id="Couleurs">
        <div id="black" title="Couleur noir" data-colo="black"></div>
        <div id="Brown" title="Couleur marron" data-colo="brown"></div>
        <div id="Red" title="Couleur rouge" data-colo="red"></div>
        <div id="Yellow" title="Couleur jaune" data-colo="yellow"></div>
        <div id="Green" title="Couleur vert" data-colo="green"></div>
        <div id="blueSoft" title="Couleur blue ciel" data-colo="deepskyblue"></div>
        <div id="blueHard" title="Couleur bleu foncé" data-colo="blue"></div>
    </article>



<script src="../../../js/Ardoise_Magique/js/class/Ardoise.class.js"></script>
<script src="../../../js/Ardoise_Magique/js/class/Palette.class.js"></script>
<script src="../../../js/Ardoise_Magique/js/class/pen.class.js"></script>
<script src="../../../js/Ardoise_Magique/js/class/program.class.js"></script>
<script src="../../../js/Ardoise_Magique/js/main.js"></script>
